GET http://localhost:9000 HTTP/1.1

###
GET  http://localhost:9000/mascotas/buscar/2 HTTP/1.1

###
GET  http://localhost:9000/mascotas/buscar HTTP/1.1

###
POST  http://localhost:9000/mascotas/crear HTTP/1.1
Content-Type: application/json

{
    "nombre":"firulais",
    "edad":2
}

###
PUT  http://localhost:9000/mascotas/actualizar/1 HTTP/1.1
Content-Type: application/json

{
    "nombre":"Abejon"
}

###
DELETE http://localhost:9000/mascotas/eliminar/3 HTTP/1.1